### ISSUE TITLE
Authentication doesn't work

### ISSUE THREAD

**Issue by dstarcev** [paritytech/ethcore-cla-bot#2]
When I authorize the application in github it redirects me to the old domain `cla.ethcore.io`, which has an invalid SSL certificate and an OAuth error

`AuthorizationError: The redirect_uri MUST match the registered callback URL for this application.
at Strategy.OAuth2Strategy.authenticate`

**Comment by 5chdn** [comment]
This should be fixed now.

**Comment by dstarcev** [comment]
Thanks
